import 'dart:io';

import 'package:dpp/src/dpp_base.dart';
import 'package:dpp/exceptions/command_failed_exception.dart';
import 'package:test/test.dart';

void main() {
  group('DartPubPublish - Rollback tests', () {
    late Directory tempDir;
    late File pubspecFile;
    late File changeLogFile;
    late File pubspec2dartFile;
    late Directory libDir;

    setUp(() async {
      tempDir = await Directory.systemTemp.createTemp('pub_publish_rollback_test');
      await Process.run('git', ['init'], workingDirectory: tempDir.path);
      await Process.run('git', ['config', 'user.email', 'test@example.com'], workingDirectory: tempDir.path);
      await Process.run('git', ['config', 'user.name', 'Test User'], workingDirectory: tempDir.path);
      await Process.run('git', ['checkout', '-b', 'main'], workingDirectory: tempDir.path);

      pubspecFile = File('${tempDir.path}/pubspec.yaml');
      final initialPubspec = '''
name: my_package
version: 1.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'
''';
      await pubspecFile.writeAsString(initialPubspec);

      changeLogFile = File('${tempDir.path}/CHANGELOG.md');
      await changeLogFile.writeAsString('## v1.0.0\n- Initial release\n');

      libDir = Directory('${tempDir.path}/lib');
      await libDir.create();
      pubspec2dartFile = File('${tempDir.path}/lib/pubspec.dart');
    });

    tearDown(() async {
      if (tempDir.existsSync()) {
        await tempDir.delete(recursive: true);
      }
    });

    test('Rolls back files when a step fails', () async {
      // Cause a failure by passing invalid arguments to a custom command if possible
      // But we can make git fail by omitting remote
      final publish = DartPubPublish(
        workingDir: tempDir.path,
        git: true, // Git push will fail because there is no remote
        analyze: false,
        format: false,
        fix: false,
        tests: false,
        pubGet: false,
        pubspec: true,
        pubspec2dart: true,
        changelog: true,
        pubPublish: false,
        verbose: false,
      );

      try {
        await publish.run('2.0.0', message: 'New feature');
      } catch (e) {
        expect(e, isA<CommandFailedException>());
      }

      // Verify rollback
      final pubspecContent = await pubspecFile.readAsString();
      expect(pubspecContent, contains('version: 1.0.0'));
      expect(pubspecContent, isNot(contains('version: 2.0.0')));

      final changelogContent = await changeLogFile.readAsString();
      expect(changelogContent, equals('## v1.0.0\n- Initial release\n'));

      // Verify pubspec.dart was deleted since it didn't exist initially
      expect(pubspec2dartFile.existsSync(), isFalse);
    });

    test('Rolls back pubspec2dart when it already existed', () async {
      final initialPubspec2dart = '''// THIS FILE WAS GENERATED BY yaml2dart. EDIT IS NOT RECOMMENDED.
const name = 'my_package';
const version = '1.0.0';
const environment = '{sdk: >=2.12.0 <3.0.0}';
''';
      await pubspec2dartFile.writeAsString(initialPubspec2dart);

      final publish = DartPubPublish(
        workingDir: tempDir.path,
        git: true, // Git push will fail because there is no remote
        analyze: false,
        format: false,
        fix: false,
        tests: false,
        pubGet: false,
        pubspec: true,
        pubspec2dart: true,
        changelog: false,
        pubPublish: false,
        verbose: false,
      );

      try {
        await publish.run('2.0.0', message: 'New feature');
      } catch (e) {
        expect(e, isA<CommandFailedException>());
      }

      // Verify pubspec.dart was rolled back, not deleted
      expect(pubspec2dartFile.existsSync(), isTrue);
      final pubspec2dartContent = await pubspec2dartFile.readAsString();
      expect(pubspec2dartContent, equals(initialPubspec2dart));
    });
  });
}
