// THIS FILE WAS GENERATED BY yaml2dart. EDIT IS NOT RECOMMENDED.
const name = 'dpp';
const description =
    'A better dart pub publish. Before publish, runs tests, fixes, lint, updates CHANGELOG, pubspec file and git commands.';
const version = '2.7.3';
const repository = 'https://github.com/insign/dart_dpp';
const executables = '{dpp: null}';
const environment = '{sdk: >=3.0.0 <4.0.0}';
const devDependencies = '{lints: ^6.0.0, test: ^1.25.2}';
const dependencies =
    '{all_exit_codes: ^2.1.0, args: ^2.4.2, json2yaml: ^3.0.1, path: ^1.9.0, pub_semver: ^2.1.4, yaml: ^3.1.2, yaml2dart: ^1.5.1}';
