// THIS FILE WAS GENERATED BY yaml2dart. EDIT IS NOT RECOMMENDED.
const name = 'dpp';
const description =
    'A better dart pub publish. Before publish, runs tests, fixes, lint, updates CHANGELOG, pubspec file and git commands.';
const version = '2.0.12';
const repository = 'https://github.com/insign/dart_dpp';
const executables = '{dpp: null}';
const environment = '{sdk: >=2.18.6 <3.0.0}';
const devDependencies = '{lints: ^2.0.0, test: ^1.21.0}';
const dependencies =
    '{all_exit_codes: ^2.1.0, args: ^2.4.0, json2yaml: ^3.0.1, path: ^1.8.3, pub_semver: ^2.1.3, yaml: ^3.1.1, yaml2dart: ^1.0.0}';
